### ISSUE TITLE
Readme file is missing

### ISSUE THREAD

**Issue by sadhakbj** [shhetri/mern-app#1]
Please provide readme file with installation steps etc.

**Comment by shhetri** [comment]
@sadhakbj Soon bro, soon. For now, just clone the repository and run `docker-compose up`. It will run both server and client. There is nothing in the client as of now but you can play with server API. Look into the code to find different endpoints. Register a user, login with username/password to get a token and call other APIs by passing token in Header.

**Comment by sadhakbj** [comment]
Thank you. Closing for now.
